apiVersion: v1
kind: Service
metadata:
  name: devops-digital-twin-service
spec:
  type: ClusterIP
  selector:
    app: devops-digital-twin
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP